### PR TITLE
Fix push hook

### LINKED ISSUE #19: Re-push produces meaningless version when push fails
https://github.com/wechaty/puppet-xp/commits/main?after=983ec43712db872ba6a92307005e119be5262dd4+69&branch=main

image

### PR DESCRIPTION
**Pull request by binsee**
Fixes #19

Need  update git-scripts to new version
link git-script/pr: https://github.com/zixia/git-scripts/pull/13

### CODE REVIEW

**Comment by huan** [comment]
Please make sure the following requirements have been met for your PR before we can continue reviewing it:

1. You have signed the CLA by clicking the `[CLA | not signed yet]` button from the comments.
2. The PR has passed all the CI tests and turns _green_. (you can execute all tests locally by running `npm test`)

**Comment by binsee** [comment]
> Please make sure the following requirements have been met for your PR before we can continue reviewing it:
> 
> 1. You have signed the CLA by clicking the `[CLA | not signed yet]` button from the comments.
> 2. The PR has passed all the CI tests and turns _green_. (you can execute all tests locally by running `npm test`)

1. done
2. The same error will be reported in the main branch

**Comment by huan** [comment]
Thanks for signing the CLA!

Yes, I see that the main branch is broken too, so we need to figure the problem out or the new version can not be published via the DevOps pipeline.

I'll have a look at it after my talk tomorrow, or it would be great if you can find any clue for the problem and try to fix it.

Thank you very much!

**Comment by binsee** [comment]
Now run `git push` continuously, no more bump versions

**Comment by binsee** [comment]
Waiting for https://github.com/zixia/git-scripts/pull/13 to merge, and run CI again

**Review by huan — CHANGES_REQUESTED** [review]
Please bump the minor version so that we can merge and publish it.

Thank you very much!

**Comment by binsee** [comment]
> Please bump the minor version so that we can merge and publish it.
> 
> Thank you very much!

done

**Review by huan — APPROVED** [review]
LGTM

Thank you very much for the improving!

**Comment by binsee** [comment]
@huan  After this pr was merged, no new npm package was automatically released.

**Comment by huan** [comment]
I have just published the new version manually. This repo has not configured the CI/CD so it has not been published automatically.

Please let me know if it works as expected, thanks for mentioning me!

**Comment by binsee** [comment]
@huan There is an error in the packaging process, the dist folder is missing, so it cannot be used correctly.

**Comment by huan** [comment]
Sorry for that, I have re-published it as 0.7.2, please try the new version.

**Comment by binsee** [comment]
I don't know why the README page for @chatie/git-scripts has no content.

https://www.npmjs.com/package/@chatie/git-scripts

**Pull request merged**
